const z = require('zod');

const companyRegistrationSchema = z.object({
  username: z.string(),
  name: z.string(),
  designation: z.string(),
  email: z.string().email(),
  password: z.string(),
  countryCode: z.string(),
  contactNumber: z.string(),
  companyType: z.string(),
  companyName: z.string(),
  tradeName: z.string(),
  legalName: z.string(),
  entityType: z.string(),
  brandNames: z.string(),
  incorporationYear: z.string(),
  registeredOfficeAddress: z.string(),
  branchAddress: z.string().optional(),
  websiteUrl: z.string().url().optional(),
  businessType: z.string(),
  sector: z.string(),
  industry: z.string(),
  minEmployeeCount: z.string(),
  maxEmployeeCount: z.string(),
  msmeRegistrationNumber: z.string(),
  cin: z.string(),
  pan: z.string(),
  gstin: z.string(),
  tradeLicenseNumber: z.string().optional(),
  iecNumber: z.string().optional(),
  aadharNumber: z.string(),
  annualTurnover: z.string().optional(),
  businessActivites: z.string().optional(),
  certifications: z.string().optional(),
  importExportCode: z.string().optional(),
  majorMarkets: z.string().optional(),
  operationLocations: z.string().optional(),
  qualityStandards: z.string().optional(),
});

const companyUpdationSchema = z.object({
  companyName: z.string().optional(),
  tradeName: z.string().optional(),
  legalName: z.string().optional(),
  companyType: z.string().optional(),
  email: z.string().email().optional(),
  countryCode: z.string().optional(),
  contactNumber: z.string().optional(),
  password: z.string().optional(),
  tagline: z.string().optional(),
  entityType: z.string().optional(),
  incorporationYear: z.string().optional(),
  registeredOfficeAddress: z.string().optional(),
  websiteUrl: z.string().url().optional(),
  businessType: z.string().optional(),
  sector: z.string().optional(),
  industry: z.string().optional(),
  minEmployeeCount: z.string().optional(),
  maxEmployeeCount: z.string().optional(),
  msmeRegistrationNumber: z.string().optional(),
  cin: z.string().optional(),
  pan: z.string().optional(),
  gstin: z.string().optional(),
  tradeLicenseNumber: z.string().optional(),
  iecNumber: z.string().optional(),
  aadharNumber: z.string().optional(),
  aboutCompany: z.string().optional(),
  aboutFounderAndTeam: z.string().optional(),
  expertise: z.string().optional(),
  annualTurnover: z.string().optional(),
  businessActivites: z.string().optional(),
  certifications: z.string().optional(),
  importExportCode: z.string().optional(),
  majorMarkets: z.string().optional(),
  operationLocations: z.string().optional(),
  qualityStandards: z.string().optional(),
});

const addProductAndServiceSchema = z.object({
  name: z.string(),
  description: z.string(),
  priceExclusiveGST: z.string(),
  gstApplicable: z.boolean(),
  modelNumber: z.string().optional(),
});

module.exports = { companyRegistrationSchema, companyUpdationSchema, addProductAndServiceSchema };
